#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Joseph Irwin <joseph.irwin.gt@gmail.com>
#


#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi


#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'


#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi


#
# Paths
#

typeset -gU cdpath fpath mailpath path

# XDG directories:

# Get basic directories or use defaults
XDG_DATA_HOME=${XDG_DATA_HOME:-"$HOME/.local/share"}
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME/.config"}
XDG_CACHE_HOME=${XDG_CACHE_HOME:-"$HOME/.cache"}

# Source user directory definitions
if [[ -f "$XDG_CONFIG_HOME/user-dirs.dirs" ]]; then
    source "$XDG_CONFIG_HOME/user-dirs.dirs"
    export \
        XDG_DATA_HOME \
        XDG_CONFIG_HOME \
        XDG_CACHE_HOME \
        XDG_DESKTOP_DIR \
        XDG_DOWNLOAD_DIR \
        XDG_TEMPLATES_DIR \
        XDG_PUBLICSHARE_DIR \
        XDG_DOCUMENTS_DIR \
        XDG_MUSIC_DIR \
        XDG_PICTURES_DIR \
        XDG_VIDEOS_DIR
fi

# Set the path to prezto
export PREZTO="$XDG_CONFIG_HOME/dotfiles/prezto"

# Set the path to use for pythonz installs
export PYTHONZ_ROOT="$XDG_DATA_HOME/pythonz"
# Set the path to use for virtualenvwrappper environments
export WORKON_HOME="$XDG_DATA_HOME/pyvenvs"

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  ${XDG_DATA_HOME%/share}/bin
  /usr/local/{bin,sbin}
  $path
)


#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-i -M -R -S -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi


#
# System Tweaks
#

# Fix TERM setting
if [[ "$TERM" == "xterm" ]]; then
  if [[ "$COLORTERM" == "Terminal" ]] || [[ "$COLORTERM" == "gnome-terminal" ]]; then
    TERM="xterm-256color"
  fi
fi

# Prevent Ubuntu from calling compinit in /etc/zsh/zshenv
skip_global_compinit=1

# Work around a bug in tmux/libevent
export EVENT_NOEPOLL=1


#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi
