#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${PREZTO}/init.zsh" ]]; then
  source "${PREZTO}/init.zsh"
fi

eval $(keychain --eval --agents ssh id_dsa 2>/dev/null)
