#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${PREZTO}/init.zsh" ]]; then
  source "${PREZTO}/init.zsh"
fi

# Use keychain to start ssh-agent/load key if not already
if [[ -f "$HOME/.ssh/id_dsa" ]]; then
  eval $(keychain --eval --agents ssh id_dsa 2>/dev/null)
fi
